BangHang/Models/OderProduct/OrderDetail.cs
using BangHang.Models.Product;
using System.ComponentModel.DataAnnotations;

namespace BangHang.Models.OderProduct
{
    public class OrderDetail
    {
        [Key]
        public int? Id { get; set; }
        public int? OrderID { get; set; }

        public int? ProductID { get; set; }

        [Display(Name = "Giá sản phẩm")]
        public decimal? Price { get; set; }

        [Display(Name = "Giảm giá còn")]
        public decimal? PriceSale { get; set; }

        [Display(Name = "Số lượng")]
        public int? Quantity { get; set; }

        [Display(Name = "Tên sản phẩm")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "{0} phải dài từ {2} đến {1} ký tự")]
        public string? NameProduct { get; set; }

        [Display(Name = "Ảnh sản phẩm")]
        public string? ImageAvata { get; set; }

        [Display(Name = "Màu sắc")]
        public string? Color { get; set; }

        [Display(Name = "Loại")]
        public string? TypeProduct { get; set; }

        [Display(Name = "Ngày tạo")]
        [DataType(DataType.DateTime)]
        public DateTime? CreateDate { get; set; }

        public virtual Order? Order { get; set; }
        public virtual Products? Product { get; set; }
    }
}

BangHang/Areas/Order/Controllers/OrderProductController.cs
using BangHang.Models;
using BangHang.Models.OderProduct;
using BangHang.Models.Services;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BangHang.Areas.Models.SendMail;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Identity;

namespace BangHang.Areas.OrderProducts.Controllers
{
    [Area("Order")]
    [Route("/order/orderproduct/[action]/{id?}")]
    public class OrderProductController : Controller
    {
        private readonly AppDbContext _context;
        private readonly CartService _cartService;
        private readonly IEmailSender _emailSender;
        private readonly MailSetting _mailSetting;
        private readonly UserManager<AppUser> _userManager;

        public OrderProductController(AppDbContext context,
                                        CartService cartService,
                                        IEmailSender emialSender,
                                        IOptions<MailSetting> mailSetting,
                                        UserManager<AppUser> userManager
                                        )
        {
            _context = context;
            _cartService = cartService;
            _emailSender = emialSender;
            _mailSetting = mailSetting.Value;
            _userManager = userManager;
        }

        [HttpGet]
        [HttpPost]
        public IActionResult Index([FromQuery(Name = "p")] int currentPage, int pageSize)
        {
            IEnumerable<Order> orders = _context.Orders.OrderByDescending(c => c.DateCreate);

            int countPage = orders.Count();
            pageSize = 5;
            int pageNumber = (int)Math.Ceiling((double)countPage / pageSize);
            if (currentPage > countPage) currentPage = countPage;
            if (currentPage < 1) currentPage = 1;
            var pagingModel = new PagingModel()
            {
                countPages = pageNumber,
                currentPage = currentPage,
                generateUrl = (pageNumber) => Url.Action("Index", new
                {
                    p = pageNumber,
                    pageSize = pageSize
                })
            };

            var qr = orders.Skip((currentPage - 1) * pageSize).Take(pageSize);

            ViewBag.OrderIndex = (currentPage - 1) * pageSize;
            ViewBag.pagingModel = pagingModel;

            return View(qr.ToList());
        }

        [HttpGet]
        public IActionResult OrderDetail(int id)
        {
            var order = _context.Orders
                        .Where(c => c.Id == id)
                        .Include(c => c.OrderDetails)
                        .FirstOrDefault();
            if (order != null)
            {
                return View(order);
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            decimal total = 0;

            var cartItems = _cartService.GetCartItems();
            List<CartItemModel> cartItemsList = new List<CartItemModel>();
            foreach (var item in cartItems)
            {
                var cart = _context.Products?
                            .Include(p => p.ProductPhoto)
                            .FirstOrDefault(p => p.Id == item.ProductId);

                cartItemsList.Add(new CartItemModel()
                {
                    Product = cart,
                    quantity = item.quantity
                });

                if (cart?.PriceSale > 0)
                {
                    total += cart.PriceSale.GetValueOrDefault() * item.quantity.GetValueOrDefault();
                }
                else
                {
                    total += cart.Price.GetValueOrDefault() * item.quantity.GetValueOrDefault();
                }

                // Save Session
                item.NameProduct = cart.Title;
                item.Price = cart.Price;
                item.PriceSale = cart.PriceSale;
                item.Color = cart.Color;
                item.TypeProduct = cart.TypeProduct;
                item.ImageAvata = cart.ProductPhoto.Select(x => x.Name).First();
            }
            _cartService.SaveCartSession(cartItems);

            var order = new Order();
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user != null)
            {
                order.CustomerName = user.FullName;
                order.Phone = user.PhoneNumber;
                order.Address = $"{user.DetailsAddress}, {user.Ward}, {user.District}, {user.City}";
                order.Email = user.Email;
            }

            ViewBag.TotalAmount = total;
            ViewBag.cartItems = cartItemsList;
            ViewBag.date = cartItemsList;
            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Order orderModel)
        {
            var cartItems = _cartService.GetCartItems();

            if (ModelState.IsValid && cartItems?.Count > 0)
            {
                // Tạo đơn hàng
                Order order = new Order()
                {
                    CustomerName = orderModel.CustomerName,
                    Phone = orderModel.Phone,
                    Email = orderModel.Email,
                    DateCreate = DateTime.Now,
                    Address = orderModel.Address,
                    Payment = orderModel.Payment,
                    TotalAmount = orderModel.TotalAmount,
                    Code = "MH" + DateTime.Now.Year.ToString()
                            + DateTime.Now.Month.ToString()
                            + DateTime.Now.Day.ToString()
                            + DateTime.Now.Hour.ToString()
                            + DateTime.Now.Minute.ToString()
                            + DateTime.Now.Second.ToString()
                };

                // creata orderdetails
                var orderDetails = new List<OrderDetail>();

                foreach (var item in cartItems)
                {
                    orderDetails.Add(new OrderDetail()
                    {
                        Order = order,
                        ProductID = item.ProductId,
                        Price = item.Price,
                        PriceSale = item.PriceSale,
                        Quantity = item.quantity,
                        NameProduct = item.NameProduct,
                        ImageAvata = item.ImageAvata,
                        TypeProduct = item.TypeProduct,
                        Color = item.Color,
                        CreateDate = order.DateCreate,
                        
                    });
                }

                await _context.OrderDetails.AddRangeAsync(orderDetails);

                var user = await _userManager.GetUserAsync(HttpContext.User);
                if (user != null)
                {
                    user.OrdersCount += 1;
                    order.UserId = user.Id;
                }

                await _context.SaveChangesAsync();

                await _emailSender.SendEmailAsync(_mailSetting.Email, $"Đơn hàng từ {order.CustomerName}", SendMailAdmin.SendEMailAdmin(order, orderDetails));
                await _emailSender.SendEmailAsync(order.Email, $"Bạm vừa đặt hàng thành công", SendMailAdmin.SendEMailClient(order, orderDetails));

                _cartService.CLearCart();

                return RedirectToAction("OrderSuccess", "Menu");
            }

            return await Create();
        }

        [HttpPost]
        public IActionResult UpdatePayment(int id, int trangthai)
        {
            var order = _context.Orders.Find(id);
            if (order != null)
            {
                order.Payment = trangthai;
                _context.SaveChanges();
                return Json(new { success = true, payment = order.Payment });
            }
            return Json(new { success = false, payment = order?.Payment });
        }
    }
}

BangHang/Areas/Order/Views/OrderProduct/Create.cshtml
@using BangHang.Models.OderProduct
@using BangHang.Models.Services
@model Order

@{
    Layout = "/Views/Shared/_LayoutHome.cshtml";
    List<CartItemModel> cartitems = ViewBag.cartItems as List<CartItemModel>;
    var total = ViewBag.TotalAmount;

}


<div class="container single_product_container mb-1">
    <div class="row">
        <div class="col">
            <div class="breadcrumbs d-flex flex-row align-items-center mb-0">
                <ul>
                    <li><a asp-action="Index" asp-controller="Menu" asp-area="Menus">Trang chủ</a></li>
                    <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Thanh toán</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="text-center col-12 mt-4">
        <h1>Thanh toán</h1>
        <p>Bạn hãy kiểm tra lại đơn hàng cho chính xác!!!</p>
    </div>
    <hr />
    @if (cartitems?.Count > 0)
    {
        <div class="row">
            <div class="col-md-7">
                <h3>Thông tin khách hàng</h3>
                <form asp-action="Create" asp-controller="OrderProduct" asp-area="Order" >
                    <input type="hidden" asp-for="TotalAmount" value="@total"/>

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="CustomerName" class="control-label"></label>
                        <input asp-for="CustomerName" class="form-control" />
                        <span  asp-validation-for="CustomerName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" type="tel" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span  asp-validation-for="Address" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span  asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Payment" class="control-label"></label>
                        <select asp-for="Payment" class="form-control" name="Payment">
                            <option value="1" selected>Thanh toán khi nhận hàng</option>
                            <option value="2">Chuyển khoản</option>
                        </select>
                        <span asp-validation-for="Payment" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input type="submit" value="Gửi" class="btn btn-success btn-block">
                    </div>
                </form>
            </div>

            <div class="col-md-5">
                <h3>Chi tiết giỏ hàng</h3>

                <table class="table">
                    @foreach (var item in cartitems)
                    {
                        
                        <tr>
                            <td>
                                <img style="width:100px" src="/Contents/Products/@item.Product?.ProductPhoto?.Select(c => c.Name).FirstOrDefault()">
                            </td>
                            <td>
                                @item.Product.Title
                            </td>
                            <td>
                                @if (item.Product.PriceSale > 0)
                                {
                                    <div class="product-price">
                                        <small style="text-decoration: line-through;">@item.Product.Price</small>
                                        <br>
                                        @item.Product.PriceSale
                                    </div>
                                }
                                else
                                {
                                    <div class="product-price">
                                        @item.Product.Price
                                    </div>
                                }
                            </td>
                            <td>
                                @( "x" + @item.quantity.ToString())
                            </td>
                        </tr>
                    }
                    <th>Tổng:</th>
                    <td></td>
                    <th>@total</th>
                </table>

            </div>
        </div>
    }
    else
    {
        <p>Không có sản phẩm nào trong giỏ hàng, hãy đi đến <a asp-action="Index" asp-area="Menus" asp-controller="Menu">trang chủ</a> để thêm sản phẩm mới</p>
    }
</div>

BangHang/Areas/Order/Views/OrderProduct/Index.cshtml
@using BangHang.Models.OderProduct
@using BangHang.Models.Services

@model List<Order>

<div class="card-header">
    <h3 class="card-title">Danh sách đơn dặt hàng</h3>

    <div class="card-body">
        <table class="table table-bordered">
            <thread>
                <tr>
                    <th>STT</th>
                    <th>Mã đơn hàng</th>
                    <th>Tên khách hàng</th>
                    <th>Số điện thoại</th>
                    <th>Tổng tiền</th>
                    <th>Loại thanh toán</th>
                    <th></th>
                </tr>
            </thread>
            <tbody>
                @if(Model?.Count > 0)
                {
                foreach (var item in Model)
                {

                <tr id="trow_@item.Id">
                    <td>@(++ViewBag.OrderIndex)</td>
                    <td>
                        <a asp-action="OrderDetail" asp-controller="OrderProduct" asp-area="Order" asp-route-id="@item.Id">
                            @item.Code
                        </a>
                    </td>
                    <td>@item.CustomerName</td>
                    <td>@item.Phone</td>
                    <td>@item.TotalAmount</td>
                    <td id="checkout_items_@item.Id" d>@(item.Payment == 1 ? "Chờ thanh toán" : "Đã thanh toán")</td>
                    <td><button class="btn btn-sm btn-primary btnCapNhat " data-id="@item.Id">Cập nhật</button></td>
                </tr>
                }
                }
            </tbody>
        </table>
    </div>
</div>
   <partial class="mt-4" name="_PagingXTL" model="@ViewBag.pagingModel">

  <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Cập nhật trạng thái</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="OrderDetailId" value="0"/>
                <div class="form-group">
                    <label>Trạng thái</label>
                    <select class="form-control" id="ddTrangThai">
                         <option value="1">Chưa thanh toán</option>
                        <option value="2">Đã thanh toán</option>
                    </select>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
              <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
              <button type="button" class="btn btn-primary btnLuu" data-dismiss="modal">Lưu</button>
            </div>
          </div>
        </div>
      </div>

@section Scripts {
    <script>
$(document).ready(function() {
    $('body').on('click', '.btnCapNhat', function() {
        var id = $(this).data("id");
        $('#OrderDetailId').val(id);
        $('#modal-default').modal('show')
    })

     $('body').on('click', '.btnLuu', function() {
        var id = $('#OrderDetailId').val();
        var trangthai = $('#ddTrangThai').val();
         $.ajax({
             url: '/order/orderproduct/updatePayment/',
             data: {id:id, trangthai:trangthai},
             type: 'POST',
             success: function(rs) {
                 if (rs.success) {
                     if (rs.payment === 2) {
                         $('#checkout_items_' + id).html("Đã thanh toán");
                     }
                     else {
                         $('#checkout_items_' + id).html("Chờ thanh toán");
                     }
                 }
             }
         })
    })
});
    </script>
}

BangHang/Areas/Order/Views/OrderProduct/OrderDetail.cshtml
@using BangHang.Models.Services
@using BangHang.Models.OderProduct
@model Order

@{
    Layout = "/Views/Shared/_LayoutAdmin.cshtml";
    int i = 1;
}

<div class="container single_product_container mb-2">
    <div class="text-center col-12 mt-4">
        <h1>Chi tiết đơn hàng</h1>
    </div>
    <hr />
    <div class="card">
        <div class="card-header">
            <h3>Thông tin khách hàng</h3>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Mã đơn hàng</label>
                        <p class="form-control">@Model.Code</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Họ tên khách hàng</label>
                        <p class="form-control">@Model.CustomerName</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Tổng tiền</label>
                        <p class="form-control">@Model.TotalAmount</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Số điện thoại</label>
                        <p class="form-control">@Model.Phone</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Ngày tạo</label>
                        <p class="form-control">@Model.DateCreate</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Email</label>
                        <p class="form-control">@Model.Email</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Trạng thái thanh toán</label>
                        <p class="form-control">@(Model.Payment == 1 ? "Chưa thanh toán" : "Đã thanh toán")</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Địa chỉ</label>
                        <p class="form-control">@Model.Address</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <h2>Danh sách sản phẩm</h2>
                </div>
                <div class="col-12">
                    <table class="table table-bordered">
                        <thread>
                            <tr>
                                <th>STT</th>
                                <th>Ảnh sản phẩm</th>
                                <th>Tên sản phẩm</th>
                                <th>Giá</th>
                                <th>Số lượng</th>
                            </tr>
                        </thread>
                        <tbody>
                            @if (Model.OrderDetails?.Count > 0)
                            {
                                foreach (var item in Model.OrderDetails)
                                {
                                    <tr>
                                        <td>@(i++)</td>
                                        <td>
                                            <img style="width:100px" src="/Contents/Products/@item.ImageAvata">
                                        </td>
                                        <td>
                                            <a asp-action="ProductSingle" asp-controller="Menu" asp-area="Menus" asp-route-id="@item.ProductID">@item.NameProduct</a>
                                        </td>
                                        <td>
                                            @if (item.PriceSale > 0)
                                            {
                                                <div class="product-price">
                                                    <small style="text-decoration: line-through;">@item.Price</small>
                                                    <br>
                                                    @item.PriceSale
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="product-price">
                                                    @item.Price
                                                </div>
                                            }
                                        </td>
                                        <td>
                                            @("x" + @item.Quantity.ToString())
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>