BangHang/Areas/Users/Controllers/PostBlogController.cs
using BangHang.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BangHang.Areas.Users.Controllers
{
    [Area("Users")]
    [Route("/postblog/[action]")]
    public class PostBlogController : Controller
    {
        private readonly AppDbContext _context;
        public PostBlogController(AppDbContext contex)
        {
            _context = contex;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var post = _context.Posts
                             .Include(x => x.PostCategory)
                            .ThenInclude(xx => xx.Category)
                            .AsNoTracking()
                            .OrderByDescending(x => x.DateCreate).ToList();

            var category = _context.Categories.ToList();
            ViewBag.Category = category;
            return View(post);
        }

        [HttpGet]
        public IActionResult PostBlogDetail(int id)
        {
            var post = _context.Posts
                            .AsNoTracking()
                            .FirstOrDefault(x => x.Id == id);

            return View(post);
        }

        [HttpGet]
        public IActionResult PostBlogCategory(int id)
        {
            var category = _context.Categories
                            .Include(x => x.CategoryChildrent)
                            .AsNoTracking()
                            .FirstOrDefault(x => x.Id == id);

            var qr = _context.Posts
                         .Include(x => x.PostCategory)   
                         .ThenInclude(xx => xx.Category)
                           .AsQueryable();

            var posts = from post1 in qr
                        where post1.PostCategory.Where(xx => xx.CategoryID == category.Id.GetValueOrDefault()).Any()
                        select post1;
            ViewBag.Category = category;
            return View(posts.ToList());
        }
    }
}

BangHang/Areas/Users/Views/PostBlog/Index.cshtml
@using BangHang.Models.Blog
@model List<Post>

@{
    var categories = ViewBag.Category as List<Category>;
}


<div class="container rounded bg-white mt-70 mb-5">
    <br />
    <div class="row">

        <div class="col-md-8 mb-4">
            <h4>Danh sách các bài viết mới nhất</h4>
            @if (Model?.Count() > 0)
            {
                foreach (var item in Model)
                {
                    <div class="card mb-4">
                        <div class="card-header p-2">

                            <ul class="nav nav-pills mb-2">
                                <li class="nav-item">
                                    <a class="nav-link active" asp-action="PostBlogCategory" asp-controller="PostBlog" asp-area="Users" asp-route-id="@item.PostCategory.Select(x => x.CategoryID).FirstOrDefault()">
                                        @item.PostCategory.Select(x => x.Category.Title).FirstOrDefault() >>
                                    </a>
                                </li>
                            </ul>
                            <p class="description">@item.Title</p>
                            <p>@item.DateCreate</p>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="active tab-pane" id="activity">
                                    <!-- Post -->
                                    <div class="post mb-3">
                                        <p>
                                            @item.DesCriptions
                                        </p>
                                        <div class="user-block mb-4">
                                            <img class="img-circle img-bordered-sm" src="/Contents/Posts/@item.Image" alt="user image">
                                        </div>
                                        <p>
                                            <span class="float-right">
                                                <a asp-action="PostBlogDetail" asp-controller="PostBlog" asp-area="Users" asp-route-id="@item.Id" class="link-black text-sm">
                                                    ... Xem thêm
                                                </a>
                                            </span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <!-- /.tab-content -->
                        </div><!-- /.card-body -->
                    </div>
                }
            }
        </div>

        <br />
        <div class="col-md-4 mb-4">
            <div class="">
                <h4>Các chuyên mục bài viết</h4>
                @if (categories?.Count() > 0)
                {
                    <ul>
                        @foreach (var item in categories)
                        {
                            <a asp-action="PostBlogCategory" asp-controller="PostBlog" asp-area="Users" asp-route-id="@item.Id">
                            <li>
                               
                                    <i class="fa fa-angle-right mb-4" aria-hidden="true"></i>
                                    <i class="fa fa-angle-right mb-4" aria-hidden="true"></i>
                                    &nbsp; @item.Title
                            </li>
                            </a>
                        }
                    </ul>
                }
            </div>
        </div>

    </div>
</div>

BangHang/Areas/Users/Views/PostBlog/PostBlogCategory.cshtml
@using BangHang.Models.Blog
@model List<Post>
@{
    var category = ViewBag.Category as Category;
}

<div class="container rounded bg-white mt-50 mb-5">

    <div class="row">
        <div class="col">
            <div class="breadcrumbs d-flex flex-row align-items-center mb-0">
                <ul>
                    <li><a asp-action="Index" asp-controller="PostBlog" asp-area="Users">Blog</a></li>
                    <li><a href="categories.html"><i class="fa fa-angle-right" aria-hidden="true"></i>Các bài viết liên quan đến @category?.Title</a></li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    <br />
@if(Model?.Count() > 0)
    {
        foreach(var item in Model)
        {
            <div class="col-md-9 mb-4">
                <div class="card">
                    <div class="card-header p-2">
                        <p class="description">@item.Title</p>
                        <p>@item.DateCreate</p>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                        <div class="tab-content">
                            <div class="active tab-pane" id="activity">
                                <!-- Post -->
                                <div class="post mb-3">
                                    <p>
                                        @item.DesCriptions
                                    </p>
                                    <div class="user-block mb-4">
                                        <img class="img-circle img-bordered-sm" src="/Contents/Posts/@item.Image" alt="user image">
                                    </div>
                                    <p>
                                        <span class="float-right">
                                            <a asp-action="PostBlogDetail" asp-controller="PostBlog" asp-area="Users" asp-route-id="@item.Id" class="link-black text-sm">
                                                ... Xem thêm
                                            </a>
                                        </span>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!-- /.tab-content -->
                    </div><!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        }
    }
</div>

BangHang/Areas/Users/Views/PostBlog/PostBlogDetail.cshtml
@using BangHang.Models.Blog
@model Post

@if(Model is not null)
{
    <div class="container rounded bg-white mt-50 mb-5">
        <div class="row">
            <div class="col">
                <div class="breadcrumbs d-flex flex-row align-items-center mb-0">
                    <ul>
                        <li><a asp-action="Index" asp-controller="PostBlog" asp-area="Users">Blog</a></li>
                        <li><a href="categories.html"><i class="fa fa-angle-right" aria-hidden="true"></i>@Model.Title</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <br />
        <div>
            <h4 class="text-center mb-4">@Model.DesCriptions</h4>
            @Html.Raw(Model.Contents)
        </div>

    </div>
}